### PR TITLE
modified my profile - jainpatel

### PR DESCRIPTION
**Pull request by jainpatel25**
please review it

### CODE REVIEW

**Comment by ShehrozIrfan** [comment]
@jainpatel25 
Great!
Your PR is merged.
You can follow me and star this repository for further details.
Have fun!

**Comment by jainpatel25** [comment]
Can you please add a hactoberfest tag

**Comment by jainpatel25** [comment]
Hey can you suggest some beginner project for contribution to hactoberfest

**Comment by ShehrozIrfan** [comment]
Hey there!
If your contribution is excluded for this repository, then please visit the repository [Ruby Rocks](https://github.com/ShehrozIrfan/ruby-rocks/) for contribution to hacktoberfest. It contains a plenty of beginner's friendly issues accepted for hacktoberfest.

Have fun!

**Pull request merged**
