### PR TITLE
Add contributor label in the readme file

### PR DESCRIPTION
**Pull request by Hariom8799**

### CODE REVIEW

**Comment by Hariom8799** [comment]
pr for #41

**Comment by Hariom8799** [comment]
pr for #36

**Comment by ShehrozIrfan** [comment]
@Hariom8799 
Great! 
Your PR is merged.
You can follow me and star this repository for further updates.
Have fun!

**Comment by ShehrozIrfan** [comment]
Hey there!
If your contribution is excluded for this repository, then please visit the repository [Ruby Rocks](https://github.com/ShehrozIrfan/ruby-rocks/) for contribution to hacktoberfest. It contains a plenty of beginner's friendly issues accepted for hacktoberfest.

Have fun!

**Pull request merged**
