### PR TITLE
Removed lines

### PR DESCRIPTION
**Pull request by shivanidotcom**
Removed Extra line 54 in the issue

### CODE REVIEW

**Comment by ShehrozIrfan** [comment]
@shivanidotcom 
Excellent. PR merged.
You can see the results on [Github Pages](https://shehrozirfan.github.io/hacktoberfest-2022-first-contribution/)

**Comment by shivanidotcom** [comment]
Yea sure thanks a lot!

**Comment by ShehrozIrfan** [comment]
@shivanidotcom 
You can follow me and star this repo for further updates.
Thanks. Have fun 👍

**Comment by ShehrozIrfan** [comment]
Hey there!
If your contribution is excluded for this repository, then please visit the repository [Ruby Rocks](https://github.com/ShehrozIrfan/ruby-rocks/) for contribution to hacktoberfest. It contains a plenty of beginner's friendly issues accepted for hacktoberfest.

Have fun!

**Comment by shivanidotcom** [comment]
Yes the repo is excluded!

**Pull request merged**
