### PR TITLE
Revert "Added myself(ARYAN SAHOO) :Updating index.html"

### PR DESCRIPTION
**Pull request by ShehrozIrfan**
Reverts ShehrozIrfan/hacktoberfest-2022-first-contribution#21

### CODE REVIEW

**Comment by AryanSahoo-2003** [comment]
Sir could you please add hacktober-accepted label otherwise it would not be counted as contribution...Could you please confirm and reply back

**Comment by ShehrozIrfan** [comment]
@AryanSahoo-2003 
You can follow me and star this repo for further updates.
Thanks. Have fun 👍

**Comment by AryanSahoo-2003** [comment]
ok sir

**Comment by ShehrozIrfan** [comment]
Hey there!
If your contribution is excluded for this repository, then please visit the repository [Ruby Rocks](https://github.com/ShehrozIrfan/ruby-rocks/) for contribution to hacktoberfest. It contains a plenty of beginner's friendly issues accepted for hacktoberfest.

Have fun!

**Pull request merged**
