### PR TITLE
milena-step

### PR DESCRIPTION
**Pull request by fideem**
hi, ive added my first contribution

### CODE REVIEW

**Comment by ShehrozIrfan** [comment]
@fideem 
Add your name in `alt` attribute.

**Comment by fideem** [comment]
done, please check :D

**Comment by ShehrozIrfan** [comment]
Hey @fideem !
Your PR is merged, you can see the results on [Github Pages](https://shehrozirfan.github.io/hacktoberfest-2022-first-contribution/)
Have fun!

**Comment by ShehrozIrfan** [comment]
@fideem 
You can follow me and star this repo for further updates.
Thanks. Have fun 👍

**Pull request merged**
